sonar.projectKey=<S4mu24>_sonar-practica
sonar.organization=<S4mu24>
sonar.projectName=Practica SonarCloud
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.source=11
sonar.host.url=https://sonarcloud.io
sonar.token=48199858b23c72447c18bd9ede0e88651acb133c
